sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libirrlicht-dev
      - libxxf86vm-dev
      - freeglut3-dev
      - gcc-4.9
      - g++-4.9
compiler:
  - gcc
env:
  matrix:
    - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=ON -DENABLE_MODULE_FEA=ON -DENABLE_MODULE_POSTPROCESS=ON -DENABLE_MODULE_VEHICLE=ON -DENABLE_CXX11=ON"
    # - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=ON  -DENABLE_MODULE_FEA=ON  -DENABLE_MODULE_POSTPROCESS=ON"
    # - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=ON  -DENABLE_MODULE_FEA=ON  -DENABLE_MODULE_POSTPROCESS=ON  -DENABLE_CXX11=ON"
    # - CMAKE_EXTRA_FLAGS="-DENABLE_MODULE_IRRLICHT=ON  -DENABLE_MODULE_VEHICLE=ON  -DENABLE_CXX11=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON "
before_install:
before_script:
  - mkdir build && cd build
  - if [ "$CXX" = "g++" ]; then CXX=g++-4.9 CC=gcc-4.9 cmake $CMAKE_EXTRA_FLAGS ..; fi
script:
  - make -j 4
  - make test
branches:
  only:
  - continuous_integration
notifications:
  recipients:
    - dariomangoni@gmail.com
  email:
    on_success: change
    on_failure: always